// ObjLoader.h : a hand-written Wavefront OBJ reader.
//
// Written by hand rather than pulled from a library because the format is
// where the interesting problem lives: OBJ stores positions, uvs and normals
// in THREE separate lists with THREE separate index streams, while the GPU
// wants one index into one vertex list. Reconciling those is the job.
#pragma once

#include "Mesh.h"

#include <filesystem>

// Supports: v / vt / vn / f, the v, v/vt, v//vn and v/vt/vn corner forms,
// negative (relative) indices, and n-gons (triangulated as a fan).
// Ignores materials (usemtl, mtllib) and grouping (o, g, s).
// Missing normals are generated by averaging face normals.
MeshData LoadObj(const std::filesystem::path& path);

// Recenters a mesh on the origin and scales it uniformly so its largest
// bounding-box dimension becomes targetSize.
//
// Models in the wild are almost never authored in your scene's units. CAD
// exports in particular arrive tens of thousands of units across and sitting
// far from the origin, which puts them outside the far plane entirely - the
// model is not invisible, it is off in the distance. Uniform scaling keeps
// the proportions, so normals stay valid without any inverse-transpose care.
void FitMeshToSize(MeshData& mesh, float targetSize);
